Ajuste de pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,11 +11,16 @@ jobs:
       - name: Checkout 🛎️
         uses: actions/checkout@v4
 
+      - name: Print current directory
+        run: pwd
+
       - name: List files in current directory
         run: ls -la
 
       - name: Change to frontend directory
-        run: cd Frontend
+        run: |
+          cd Frontend || { echo "Failed to change directory"; exit 1; }
+          pwd
 
       - name: List files in frontend directory
         run: ls -la
